openapi: '3.0.0'
info:
  version: 'beta'
  title: 'A(i)ppealing Companies'
  description: Create visually appealing images of company producs made of chocolate, gold or lego based on AI

paths:

  # get individual company
  /companies/{companyId}:
    get:
      summary: Get company
      description: Get company and its a(i)ppealing associations
      operationId: getCompany
      tags:
        - companies
      parameters:
        - name: companyId
          in: path
          description: Company ID
          required: true
          schema:
            type: string
          example: fleurop

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
              examples:
                example-fleurop:
                    value:
                        id: fleurop
                        name: 'Fleurop / yousendmeflowers / main'
                        city: '{{$randomCity}}'
                        motto: '{{$randomCatchPhrase}}'
                        description: 'Fleurop is a flower delivery service with a network of florists in 140 countries. YouSendMeFlowers is a similar service in the US. Main is a flower delivery service in the Netherlands.'
                        associations:
                          - id: flowers
                            name: 'Flowers'
                            type: 'product'
                            url: 'https://user-images.githubusercontent.com/1872314/208254526-fe40f349-5456-4549-b72d-e49fe341f8e7.png'
                example-lexus:
                    value:
                        id: lexus
                        name: 'Lexus'
                        description: "Lexus is the luxury vehicle division of the Japanese automaker Toyota. The Lexus brand is marketed in more than 70 countries and territories worldwide and has become Japan's largest-selling make of premium cars."
                        city: 'Toyota City'
                        motto: 'The Pursuit of Perfection'
                        associations:
                          - id: lexus-ux
                            name: 'Lexus UX'
                            type: 'product'
                            url: 'https://user-images.githubusercontent.com/1872314/208254307-d1971475-31aa-4c10-ac8d-7b907579438d.png'    
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /companies:
    get:
      summary: List all companies
      description: List all companies and their a(i)ppealing associations
      operationId: listCompanies
      tags:
        - companies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array   
                items:
                  $ref: '#/components/schemas/Company'
              example:
                - id: main
                  name: 'Fleurop / yousendmeflowers / main'
                  city: '{{$randomCity}}'
                  motto: '{{$randomCatchPhrase}}'
                  description: 'Fleurop is a flower delivery service with a network of florists in 140 countries. YouSendMeFlowers is a similar service in the US. Main is a flower delivery service in the Netherlands.'
                  associations:
                    - id: flowers
                      name: 'Flowers'
                      type: 'product'
                      url: 'https://user-images.githubusercontent.com/1872314/208254526-fe40f349-5456-4549-b72d-e49fe341f8e7.png'
                - id: "volkswagen"
                  name: 'Volkswagen'
                  description: 'Volkswagen AG is a German multinational automotive manufacturing company headquartered in Wolfsburg, Lower Saxony, Germany.'
                  city: 'Wolfsburg'
                  motto: 'Das Auto'
                  associations:
                    - id: vw-caravan
                      name: 'VW Caravan'
                      type: 'product'
                      url: 'https://user-images.githubusercontent.com/1872314/208270572-17d0d771-17d5-4e95-ab1c-6ebc86432bb9.png'
                    - id: porsche-911
                      name: 'Porsche 911'
                      type: 'product'
                      url: 'https://user-images.githubusercontent.com/1872314/208270526-6b8dd152-674e-4496-835f-671882e70d1b.png'
                - id: 'lexus'
                  name: 'Lexus'
                  city: 'Toyota'
                  motto: 'The Pursuit of Perfection'
                  description: "Lexus is the luxury vehicle division of the Japanese automaker Toyota. The Lexus brand is marketed in more than 70 countries and territories worldwide and has become Japan's largest-selling make of premium cars."
                  associations:
                    - id: lexus-ux
                      name: 'Lexus UX'
                      type: 'product'
                      url: 'https://user-images.githubusercontent.com/1872314/208254307-d1971475-31aa-4c10-ac8d-7b907579438d.png'
                - id: 'allianz'
                  name: 'Allianz'
                  city: 'Munich'
                  motto: 'Together. Stronger.'
                  description: 'Allianz SE is a German multinational financial services company headquartered in Munich, Bavaria. It is the largest insurance company in the world by revenue.'
                  associations:
                    - id: allianz-arena
                      name: 'Allianz Arena'
                      type: 'product'
                      url: "https://user-images.githubusercontent.com/1872314/208270631-87b3c79c-c6e8-47dd-9cf2-52451989b83b.png"
                
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the company
        name:
          type: string
          description: The name of the company
        description:
          type: string
          description: The description of the company
        city:
          type: string
          description: City associated with company
        motto:
          type: string
          description: Motto associated with company
        associations:
          type: array
          items:
            $ref: '#/components/schemas/Association'
        
    Association:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: The unique identifier of the association
        name:
          type: string
          description: The name of the association
        type:
          type: string
          description: The type of the association
          enum:
            - service
            - product
        description:
          type: string
          description: The description of the association
        url:
          type: string
          format: uri
          description: The a(i)ppealing image generated with the association 
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []