openapi: '3.0.0'
info:
  version: 'alpha'
  title: 'A(i)ppealing Companies'
  description: Create visually appealing images of the products and services companies are known for using AI image generation and text completion

paths:

  /companies:
    get:
      summary: List all companies
      description: List all companies and their a(i)ppealing associations
      operationId: listCompanies
      tags:
        - companies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                example:
                  - id: 0
                    name: 'Fleurop / yousendmeflowers / main'
                    description: 'Fleurop is a flower delivery service with a network of florists in 140 countries. YouSendMeFlowers is a similar service in the US. Main is a flower delivery service in the Netherlands.'
                    associations:
                      - id: 0
                        name: 'Flowers'
                        type: 'product'
                        url: 'https://user-images.githubusercontent.com/1872314/208254526-fe40f349-5456-4549-b72d-e49fe341f8e7.png'
                  - id: 1
                    name: 'Volkswagen'
                    description: 'Volkswagen AG is a German multinational automotive manufacturing company headquartered in Wolfsburg, Lower Saxony, Germany.'
                    associations:
                      - id: 1
                        name: 'VW Caravan'
                        type: 'product'
                        uri: 'https://oaidalleapiprodscus.blob.core.windows.net/private/org-c84hkx2pcVBjsfWLkVgEUsVt/user-rSSV7en2wQibbQJa17CJvcOT/img-1veblWwlTNCztPx9i1Dadf8E.png?st=2022-12-17T16%3A27%3A50Z&se=2022-12-17T18%3A27%3A50Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2022-12-17T13%3A19%3A43Z&ske=2022-12-18T13%3A19%3A43Z&sks=b&skv=2021-08-06&sig=SFZu2ZZWIvb%2Bon%2BXjBt%2BUd%2Bv/qmMtGwttajr7i9nUK0%3D'
                      - id: 2
                        name: 'Porsche 911'
                        type: 'product'
                        url: 'https://oaidalleapiprodscus.blob.core.windows.net/private/org-c84hkx2pcVBjsfWLkVgEUsVt/user-rSSV7en2wQibbQJa17CJvcOT/img-MyhalYcYpGunNProZj8ORQdx.png?st=2022-12-17T16%3A26%3A04Z&se=2022-12-17T18%3A26%3A04Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2022-12-17T13%3A45%3A48Z&ske=2022-12-18T13%3A45%3A48Z&sks=b&skv=2021-08-06&sig=asXR32Sb%2B7rEyR9dRb9SvmS/x04G4sJ4fDYVHUiCGn0%3D'
                  - id: 2
                    name: 'Lexus'
                    description: "Lexus is the luxury vehicle division of the Japanese automaker Toyota. The Lexus brand is marketed in more than 70 countries and territories worldwide and has become Japan's largest-selling make of premium cars."
                    associations:
                      - id: 3
                        name: 'Lexus UX'
                        type: 'product'
                        url: 'https://user-images.githubusercontent.com/1872314/208254307-d1971475-31aa-4c10-ac8d-7b907579438d.png'
                items:
                  $ref: '#/components/schemas/Company'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    company:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier of the company
        name:
          type: string
          description: The name of the company
        description:
          type: string
          description: The description of the company
        city:
          type: string
          description: City associated with company
        motto:
          type: string
          description: Motto associated with company
        associations:
          type: array
          items:
            $ref: '#/components/schemas/Association'
        
    Association:
      type: object
      required:
        - id
        - name
        - type
      properties:
        name:
          type: string
          description: The name of the association
        type:
          type: string
          description: The type of the association
          enum:
            - service
            - product
        description:
          type: string
          description: The description of the association
        url:
          type: string
          format: uri
          description: The a(i)ppealing image generated with the association 
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []